-- Rescued from the Railway database before the Cloudflare migration.
-- Generated 2026-08-14T16:12:08.672Z
-- Applications are appended separately: exporting them needs a login.

DELETE FROM projects;
INSERT INTO projects (id,title,case_label,status,tags,link,image_url,desc_en,desc_uk) VALUES (0,'MASTER THE BLADE','CASE 001 — 2026','● LIVE','CLOUDFLARE, JS, LANDING','https://ronin-forge.store','/uploads/mrnm4by1-66ba9060.jpg','A ONE-PAGE WEBSITE DESIGNED TO SELL CUSTOM-MADE KATANAS ON ORDER.','ОДНОСТОРІНКОВИЙ САЙТ З МЕТОЮ ПРОДАЖУ КАСТОМНИХ КАТАН НА ЗАМОВЛЕННЯ.');
INSERT INTO projects (id,title,case_label,status,tags,link,image_url,desc_en,desc_uk) VALUES (1,'МЕЛМАН','CASE 002 — 2026','● LIVE','E-COMMERCE, JS, NETLIFY','https://melman.shop/','img/melman.png','MERCH STORE FOR THE #1 OSTRICH IN UKRAINIAN TIKTOK.','МАГАЗИН МЕРЧУ СТРАУСА №1 В УКРАЇНСЬКОМУ ТІКТОК.');
INSERT INTO projects (id,title,case_label,status,tags,link,image_url,desc_en,desc_uk) VALUES (2,'JeMonty','CASE 003 — 2026','● LIVE','E-COMMERCE, JS, SHOP, CloudFlare','https://jemonty.shop/','/uploads/mskbrgsf-1be063a4270dfeda.jpg','French cuisine restaurant, with professional chef JeMonty','Ресторан Французької кухні, з професійним шефом JeMonty');
INSERT INTO projects (id,title,case_label,status,tags,link,image_url,desc_en,desc_uk) VALUES (3,'ORLEVAN SHOP','CASE 004 — 2026','● LIVE','E-COMMERCE, NodeJS, Versel, CloudFlare, Google Analytics','https://www.orlevan.store/','/uploads/mst565u2-bb5b28e32b55bd27.jpg','Online store of handmade custom jewelry!','Онлайн - магазин, ювелірних виробів ручної роботи, під замовлення!');

DELETE FROM team_members;
INSERT INTO team_members (id,sort_order,is_builtin,code,name_en,name_uk,role_en,role_uk,location_en,location_uk,bio_en,bio_uk,status,skills,photo_url) VALUES ('sv-001',0,1,'#SV-001','YAROSLAV','ЯРОСЛАВ','FOUNDER / DEVELOPER','ЗАСНОВНИК / РОЗРОБНИК','UKRAINE','УКРАЇНА','BUILDS FAST, DETAILED WEBSITES AND AUTOMATION — FROM DESIGN TO DEPLOYED PRODUCT.','СТВОРЮЄ ШВИДКІ, ДЕТАЛЬНІ САЙТИ ТА АВТОМАТИЗАЦІЮ — ВІД ДИЗАЙНУ ДО ГОТОВОГО ПРОДУКТУ.','online','[{"label_en":"FRONTEND","label_uk":"FRONTEND","level":9},{"label_en":"DESIGN","label_uk":"ДИЗАЙН","level":10},{"label_en":"BACKEND","label_uk":"BACKEND","level":9},{"label_en":"AI / AUTOMATION","label_uk":"AI / АВТОМАТИЗАЦІЯ","level":8},{"label_en":"DEVOPS","label_uk":"DEVOPS","level":10}]','img/yaroslav.jpg');
INSERT INTO team_members (id,sort_order,is_builtin,code,name_en,name_uk,role_en,role_uk,location_en,location_uk,bio_en,bio_uk,status,skills,photo_url) VALUES ('sv-002',1,1,'#SV-002','OLEKSANDR','ОЛЕКСАНДР','COLLABORATOR','ПАРТНЕР','UKRAINE','УКРАЇНА','FULL-STACK DEVELOPER WITH A FOCUS ON AUTOMATION AND QUALITY.','FULL-STACK РОЗРОБНИК З ФОКУСОМ НА АВТОМАТИЗАЦІЮ ТА ЯКІСТЬ.','atwork','[{"label_en":"FRONTEND","label_uk":"FRONTEND","level":7},{"label_en":"BACKEND","label_uk":"BACKEND","level":8},{"label_en":"DEVOPS","label_uk":"DEVOPS","level":6},{"label_en":"DESIGN","label_uk":"ДИЗАЙН","level":6}]','img/oleksandr.jpg');
INSERT INTO team_members (id,sort_order,is_builtin,code,name_en,name_uk,role_en,role_uk,location_en,location_uk,bio_en,bio_uk,status,skills,photo_url) VALUES ('sv-003',2,1,'#SV-003','ROMAN','РОМАН','PARTNER','ПАРТНЕР','UKRAINE','УКРАЇНА','FRONT-END DEVELOPER BUILDING FAST, PIXEL-PERFECT INTERFACES.','FRONT-END РОЗРОБНИК, СТВОРЮЄ ШВИДКІ, ПІКСЕЛЬ-ПЕРФЕКТНІ ІНТЕРФЕЙСИ.','offline','[{"label_en":"FRONTEND","label_uk":"FRONTEND","level":10},{"label_en":"BACKEND","label_uk":"BACKEND","level":8},{"label_en":"DESIGN","label_uk":"ДИЗАЙН","level":6},{"label_en":"DEVOPS","label_uk":"DEVOPS","level":8}]','img/roman.jpg');
